FROM python:3.12-slim

WORKDIR /app

COPY ./rest-api /app/rest-api
COPY ./pylib /app/pylib

RUN pip install --no-cache-dir -r /app/rest-api/requirements.txt

ENV PYTHONPATH=/app:/app/pylib
ENV DB_NAME=simlab
ENV MONGO_URI=mongodb://mongodb:27017/?replicaSet=rs0
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["python", "/app/rest-api/main.py"]
