FROM node:22-alpine AS build

WORKDIR /app

COPY ./gui/simlab/package*.json ./
RUN npm ci

COPY ./gui/simlab ./

ARG VITE_API_BASE_URL=/api/v1
ARG VITE_API_KEY=simlab-api-key42

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_API_KEY=${VITE_API_KEY}

RUN npm run build

FROM nginx:1.27-alpine

COPY ./gui/simlab/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
