CONTIKI_PROJECT = udp-client udp-server
all: $(CONTIKI_PROJECT)

CONTIKI = ../..

#To enable TSCH
MAKE_MAC = MAKE_MAC_TSCH
include $(CONTIKI)/Makefile.dir-variables

include $(CONTIKI)/Makefile.include
